# Generated by Django 3.0.2 on 2020-01-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('openPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
